# Generated by Django 4.2.2 on 2023-06-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='latitude',
            field=models.DecimalField(decimal_places=30, max_digits=30),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='longitude',
            field=models.DecimalField(decimal_places=30, max_digits=30),
        ),
    ]
