# Generated by Django 4.2.2 on 2023-06-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_tracking_latitude_alter_tracking_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='latitude',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='longitude',
            field=models.CharField(max_length=30),
        ),
    ]
